### ISSUE TITLE
java.lang.ClassCastException: android.util.ArrayMap cannot be cast to java.util.HashMap

### ISSUE THREAD

**Issue by hasanmumin** [VivekPanyam/Evolve#16]
Hi,
i try to use your lib, but Utils class line number 32 have class cast exception.

i using your DynamicApp.

```
W/System.err: java.lang.reflect.InvocationTargetException
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err:     at com.tvmatches.autoupdate.DynamicApp.init(DynamicApp.java:91)
W/System.err:     at com.tvmatches.autoupdate.MainActivity.onCreate(MainActivity.java:16)
W/System.err:     at android.app.Activity.performCreate(Activity.java:5990)
W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:151)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:135)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/System.err: Caused by: java.lang.ClassCastException: android.util.ArrayMap cannot be cast to java.util.HashMap
W/System.err:     at com.vivekpanyam.evolve.Utils.setClassLoader(Utils.java:36)
W/System.err:     at com.vivekpanyam.evolve.Evolve.init(Evolve.java:138)
```

**Comment by saikumar100** [comment]
Hi,

 Even I got the same issue. Have you found any workaround for this issue.

Thanks,
Nick

**Comment by sugarp** [comment]
I got stucked here aswell. Anyone has solved it?
