### ISSUE TITLE
com.android.dx.cf.iface.ParseException

### ISSUE THREAD

**Issue by codeskraps** [VivekPanyam/Evolve#2]
I'm getting a ParseException on the CustomClassLoader finClass method line 68

```
df.addClass(new File(context.getFilesDir(), name.replace('.', File.separatorChar) + ".class"));
```

This is the Exception thrown (line numbers may be a bit different as I've been debugging this):

```
02-26 15:17:43.958: I/CustomClassLoader(19260): Handled: findClass: com.vivekpanyam.evolve.dummy.Dummy1
02-26 15:17:43.958: I/CustomClassLoader(19260): com.android.dx.cf.iface.ParseException: class name (com/vivekpanyam/evolve/dummy/Dummy1) does not match path (Dummy1.class)
02-26 15:17:43.958: I/CustomClassLoader(19260):     at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:510)
02-26 15:17:43.958: I/CustomClassLoader(19260):     at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:396)
02-26 15:17:43.958: I/CustomClassLoader(19260):     at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:378)
02-26 15:17:43.958: I/CustomClassLoader(19260):     at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:241)
02-26 15:17:43.958: I/CustomClassLoader(19260):     at com.android.dx.dex.cf.CfTranslator.translate0(CfTranslator.java:112)
02-26 15:17:43.958: I/CustomClassLoader(19260):     at com.android.dx.dex.cf.CfTranslator.translate(CfTranslator.java:87)
02-26 15:17:43.958: I/CustomClassLoader(19260):     at javassist.android.DexFile.addClass(DexFile.java:23)
02-26 15:17:43.958: I/CustomClassLoader(19260):     at com.vivekpanyam.evolve.CustomClassLoader.findClass(CustomClassLoader.java:71)
02-26 15:17:43.958: I/CustomClassLoader(19260):     at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
02-26 15:17:43.958: I/CustomClassLoader(19260):     at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
02-26 15:17:43.958: I/CustomClassLoader(19260):     at java.lang.Class.classForName(Native Method)
02-26 15:17:43.958: I/CustomClassLoader(19260):     at java.lang.Class.forName(Class.java:217)
02-26 15:17:43.958: I/CustomClassLoader(19260):     at com.vivekpanyam.evolve.Evolve.getDummy(Evolve.java:181)
02-26 15:17:43.958: I/CustomClassLoader(19260):     at com.vivekpanyam.evolve.DynamicActivity.startActivityForResult(DynamicActivity.java:70)
02-26 15:17:43.958: I/CustomClassLoader(19260):     at android.app.Activity.startActivity(Activity.java:3566)
02-26 15:17:43.958: I/CustomClassLoader(19260):     at android.app.Activity.startActivity(Activity.java:3534)
02-26 15:17:43.958: I/CustomClassLoader(19260):     at com.instillo.appdownloader.home.SplashActivity$1.run(SplashActivity.java:92)
02-26 15:17:43.958: I/CustomClassLoader(19260):     at java.lang.Thread.run(Thread.java:856)
```

**Comment by VivekPanyam** [comment]
Add the line `cf_options.strictNameCheck = false;` before [this line](https://github.com/crimsonwoods/javassist-android/blob/master/javassist-android/src/javassist/android/DexFile.java#L23) in DexFile.java. This disables strict file-name-vs-class-name checking. I forgot to put that in the readme. Thanks!
