### ISSUE TITLE
Resources$NotFoundException on setContentView(R.id.layout)

### ISSUE THREAD

**Issue by codeskraps** [VivekPanyam/Evolve#3]
I'm getting a <code>Resources$NotFoundException</code> while trying to set the layout on the Activity using a resource id.

I see you override the <code>getResources()</code> on you <code>DynamicActivity</code> which I'm guessing <code>setContentView</code> may  be bypassing.

Is there any other way to set the layout using resources or will I have to inflate the layout from xml and set the returned View??

Exception:

```
02-26 16:30:33.868: E/AndroidRuntime(21009): FATAL EXCEPTION: main
02-26 16:30:33.868: E/AndroidRuntime(21009): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.vivekpanyam.TestApp/com.vivekpanyam.evolve.dummy.Dummy1}: android.content.res.Resources$NotFoundException: Resource ID #0x7f030009
02-26 16:30:33.868: E/AndroidRuntime(21009):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at android.app.ActivityThread.access$600(ActivityThread.java:141)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at android.os.Handler.dispatchMessage(Handler.java:99)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at android.os.Looper.loop(Looper.java:137)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at android.app.ActivityThread.main(ActivityThread.java:5041)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at java.lang.reflect.Method.invokeNative(Native Method)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at java.lang.reflect.Method.invoke(Method.java:511)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at dalvik.system.NativeStart.main(Native Method)
02-26 16:30:33.868: E/AndroidRuntime(21009): Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f030009
02-26 16:30:33.868: E/AndroidRuntime(21009):    at android.content.res.Resources.getValue(Resources.java:1014)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2139)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at android.content.res.Resources.getLayout(Resources.java:853)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at android.view.LayoutInflater.parseInclude(LayoutInflater.java:785)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:736)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:270)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at android.app.Activity.setContentView(Activity.java:1881)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at com.instillo.appdownloader.home.DownloaderActivity.onCreate(DownloaderActivity.java:68)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at android.app.Activity.performCreate(Activity.java:5104)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
02-26 16:30:33.868: E/AndroidRuntime(21009):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
02-26 16:30:33.868: E/AndroidRuntime(21009):    ... 11 more
```

**Comment by codeskraps** [comment]
Inflating the layout from resources produces the same issue...

```
View view = mInflater.inflate(R.layout.layout, null);
```

Does this mean the only way to create Views is programmatically or I may missing something

**Comment by VivekPanyam** [comment]
setContentView should work. Have you taken a look at [EvolveWrapper](https://github.com/VivekPanyam/EvolveWrapper)? What version of Android are you testing on? Is the code up somewhere?

Unfortunately, Android has changed a lot and I haven't worked on Evolve much since last year (hence the ridiculously late response to this issue). However, I'd be glad to take any pull requests/help with issues!

I may continue active development if there's enough interest.

**Comment by codeskraps** [comment]
I since then stopped working on the project and move to a different company. I can't remember with certanty which version of Android I was testing this but I'm pretty sure it was 4+.

Sorry I can't give more information.

**Comment by ravanova** [comment]
I have managed to 'solve' this issue today, after having it for the last few days!
I was loading in an apk which did not come from a Gradle project, so I converted the project to Gradle. This still wasn't enough, so I created a new Gradle project and copied over the files.

Working with Android 16.

**Comment by ravanova** [comment]
I re-encountered the issue, as I had left out the "extends DynamicActivity" in my main Activity class!
