### ISSUE TITLE
I got error: Didn't find class on path DexPathLis... How can I solve it?

### ISSUE THREAD

**Issue by bigbn** [VivekPanyam/Evolve#6]
```
02-27 21:15:17.317    3246-3246/me.about.bigbn.promostackshell E/AndroidRuntime﹕ FATAL EXCEPTION: mainjava.lang.RuntimeException: Unable to instantiate activity ComponentInfo{me.about.bigbn.promostackshell/me.about.bigbn.promostack.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "me.about.bigbn.promostack.MainActivity" on path: DexPathList[[zip file "/data/app/me.about.bigbn.promostackshell-1.apk"],nativeLibraryDirectories=[/data/app-lib/me.about.bigbn.promostackshell-1, /vendor/lib, /system/lib]]
          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282)
          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2408)
          at android.app.ActivityThread.access$600(ActivityThread.java:167)
          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
          at android.os.Handler.dispatchMessage(Handler.java:107)
          at android.os.Looper.loop(Looper.java:194)
          at android.app.ActivityThread.main(ActivityThread.java:5405)
          at java.lang.reflect.Method.invokeNative(Native Method)
          at java.lang.reflect.Method.invoke(Method.java:525)
          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:838)
          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
          at dalvik.system.NativeStart.main(Native Method)
   Caused by: java.lang.ClassNotFoundException: Didn't find class "me.about.bigbn.promostack.MainActivity" on path: DexPathList[[zip file "/data/app/me.about.bigbn.promostackshell-1.apk"],nativeLibraryDirectories=[/data/app-lib/me.about.bigbn.promostackshell-1, /vendor/lib, /system/lib]]
          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
          at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
          at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
          at android.app.Instrumentation.newActivity(Instrumentation.java:1124)
          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2273)
          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2408)
          at android.app.ActivityThread.access$600(ActivityThread.java:167)
          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
          at android.os.Handler.dispatchMessage(Handler.java:107)
          at android.os.Looper.loop(Looper.java:194)
          at android.app.ActivityThread.main(ActivityThread.java:5405)
          at java.lang.reflect.Method.invokeNative(Native Method)
          at java.lang.reflect.Method.invoke(Method.java:525)
          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:838)
          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
          at dalvik.system.NativeStart.main(Native Method)
```

I think i miss something, but cant make it work. Here is the souces of my wrapper if it can be helpful:
https://github.com/bigbn/PromoStackShell
APK file exist and based on DinamicActivity, original Activity in file described as:

```
<activity
    android:screenOrientation="landscape"
    android:name="me.about.bigbn.promostack.MainActivity"
    android:configChanges="orientation|keyboardHidden|screenSize"
    android:label="@string/app_name"
    android:theme="@android:style/Theme.NoTitleBar.Fullscreen" >
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>

</activity>
```

Project was created in AndroidStudio and uses gradle for build;

**Comment by VivekPanyam** [comment]
Do you have the main application on GitHub too? Also make sure you have the wrapper set up the same way as the example. Your wrapper's AndroidManifest doesn't contain dummy classes. See the [sample manifest](https://github.com/VivekPanyam/EvolveWrapper/blob/master/AndroidManifest.xml).

Also your main APK must be in the assets directory of the wrapper. This APK is what is used on first launch.

Hopefully that helps!

**Comment by bigbn** [comment]
Oh. i dont know what to do. I found that signature check is one of the reasons, because it everytime fails, because i use signed app in not signed wrapper, but anyway problem still the same

```
02-28 12:26:37.195  12591-12591/me.about.bigbn.promostackshell W/System.err﹕java.lang.ClassNotFoundException: me.about.bigbn.promostack.MainActivity
```

and new one

```
02-28 12:26:37.197  12591-12591/me.about.bigbn.promostackshell W/System.err﹕ Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
02-28 12:26:37.197  12591-12591/me.about.bigbn.promostackshell W/System.err﹕ at dalvik.system.DexFile.defineClass(Native Method)
02-28 12:26:37.197  12591-12591/me.about.bigbn.promostackshell W/System.err﹕ at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:211)
02-28 12:26:37.197  12591-12591/me.about.bigbn.promostackshell W/System.err﹕ at dalvik.system.DexPathList.findClass(DexPathList.java:313)
02-28 12:26:37.197  12591-12591/me.about.bigbn.promostackshell W/System.err﹕ at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:51)
02-28 12:26:37.197  12591-12591/me.about.bigbn.promostackshell W/System.err﹕ at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
02-28 12:26:37.197  12591-12591/me.about.bigbn.promostackshell W/System.err﹕ at java.lang.ClassLoader.loadClass(ClassLoader.java:495)
02-28 12:26:37.197  12591-12591/me.about.bigbn.promostackshell W/System.err﹕ at java.lang.ClassLoader.loadClass(ClassLoader.java:495)
02-28 12:26:37.198  12591-12591/me.about.bigbn.promostackshell W/System.err﹕ at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
02-28 12:26:37.198  12591-12591/me.about.bigbn.promostackshell W/System.err﹕ ... 18 more
```

**Comment by bigbn** [comment]
The story continues... Now my activity class found, but compiler say that he cant load a superclass(DynamicActivity i think):

```
03-01 12:14:55.569  16994-16994/me.about.bigbn.promostackshell W/dalvikvm﹕ Class resolved by unexpected DEX: Lme/about/bigbn/promostack/MainActivity;(0x41b1a7e0):0x61f18000 ref [Lcom/vivekpanyam/evolve/DynamicActivity;] Lcom/vivekpanyam/evolve/DynamicActivity;(0x41b0e0d8):0x61c39000
03-01 12:14:55.569  16994-16994/me.about.bigbn.promostackshell W/dalvikvm﹕ (Lme/about/bigbn/promostack/MainActivity; had used a different Lcom/vivekpanyam/evolve/DynamicActivity; during pre-verification)
03-01 12:14:55.569  16994-16994/me.about.bigbn.promostackshell W/dalvikvm﹕ Unable to resolve superclass of Lme/about/bigbn/promostack/MainActivity; (1685)
03-01 12:14:55.569  16994-16994/me.about.bigbn.promostackshell W/dalvikvm﹕ Link of class 'Lme/about/bigbn/promostack/MainActivity;' failed
03-01 12:14:55.569  16994-16994/me.about.bigbn.promostackshell W/System.err﹕ java.lang.ClassNotFoundException: me.about.bigbn.promostack.MainActivity
```

but i still can't make it work

**Comment by bigbn** [comment]
I got stuck for several days and could not find the solution.
Could you please let me know the root cause of above error and how to fix
it?

**Comment by VivekPanyam** [comment]
Based on the errors you're getting, it looks like there may be an issue with the way you're building the projects.

Note that the Evolve library should only be included in the main application. It looks like you included the jar in the wrapper application. This may be why there are some dependency issues. Unfortunately, I can't really be more helpful without looking at both the wrapper and the main project. Feel free to comment on this issue if you have more questions!

**Comment by Goldie13** [comment]
Java.Lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.Android.MyPro/com.Android.MyPro.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.Android.MyPro.MainActivity" on path: DexPathList[[zip file "/data/app/com.Android.Mercedes-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.Android.Mercedes-1, /vendor/lib, /system/lib, /system/lib/arm]] ---> Java.Lang.ClassNotFoundException: Didn't find class "com.Android.MyPro.MainActivity" on path: DexPathList[[zip file "/data/app/com.Android.Mercedes-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.Android.Mercedes-1, /vendor/lib, /system/lib, /system/lib/arm]]
  at --- End of managed Java.Lang.ClassNotFoundException stack trace ---
  at java.lang.ClassNotFoundException: Didn't find class "com.Android.MyPro.MainActivity" on path: DexPathList[[zip file "/data/app/com.Android.Mercedes-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.Android.MyPro-1, /vendor/lib, /system/lib, /system/lib/arm]]
  at at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
  at at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2141)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2273)
  at at android.app.ActivityThread.access$800(ActivityThread.java:138)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1236)
  at at android.os.Handler.dispatchMessage(Handler.java:102)
  at at android.os.Looper.loop(Looper.java:149)
  at at android.app.ActivityThread.main(ActivityThread.java:5045)
  at at java.lang.reflect.Method.invokeNative(Native Method)
  at at java.lang.reflect.Method.invoke(Method.java:515)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
  at at dalvik.system.NativeStart.main(Native Method)
  --- End of inner exception stack trace ---
  at --- End of managed Java.Lang.RuntimeException stack trace ---
  at java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.Android.Mercedes/com.Android.MyPro.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.Android.MyPro.MainActivity" on path: DexPathList[[zip file "/data/app/com.Android.Mercedes-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.Android.MyPro-1, /vendor/lib, /system/lib, /system/lib/arm]]
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2150)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2273)
  at at android.app.ActivityThread.access$800(ActivityThread.java:138)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1236)
  at at android.os.Handler.dispatchMessage(Handler.java:102)
  at at android.os.Looper.loop(Looper.java:149)
  at at android.app.ActivityThread.main(ActivityThread.java:5045)
  at at java.lang.reflect.Method.invokeNative(Native Method)
  at at java.lang.reflect.Method.invoke(Method.java:515)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
  at at dalvik.system.NativeStart.main(Native Method)
  at Caused by: java.lang.ClassNotFoundException: Didn't find class "com.Android.MyPro.MainActivity" on path: DexPathList[[zip file "/data/app/com.Android.MyPro-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.Android.MyPro-1, /vendor/lib, /system/lib, /system/lib/arm]]
  at at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
  at at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2141)
  at ... 11 more

I working on Implicit Intent sharing in which I am sharing image from galleey to my demo application.
I am using Xamarin Visual Studio 2013.
Looking forward for your reply...

**Comment by yangguanglu** [comment]
hello guy,I meet the same question as you.I just delete all the fold named "build" and build it again,then it's good.

**Comment by weizhizhanghao** [comment]
step 1：please check your package name and activity name is right?

step2: if no: corrected  it , after,if it is still incorrect, go to step3. 

step 2: if yes: check your android studio version ,if version is upper than 2.0, then open your android setting,find the Install Run , cancle all the checked button, then, run once again, you will find, you have solved this problem.  if the version is less than 2.0, i have no way to solve....

reason: android studio 2.0 and upper version add a new function named fast install, then, it will reserve some infomations, but when you run your project the next time, it doesn't recognize the change, then it will lead to some bad results.
